name: "Build"

on:
  pull_request:
    branches: [main]
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu
          ## Lint all sources
          - name: Ubuntu - lint
            os: ubuntu-24.04
            lint: true
          ## Release
          - name: Ubuntu - release
            os: ubuntu-24.04
            build_type: Release
            sanitize: none
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    env:
      JANK_MATRIX_ID: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.sanitize }}
      JANK_BUILD_TYPE: ${{ matrix.build_type }}
      JANK_LINT: ${{ matrix.lint }}
      JANK_COVERAGE: ${{ matrix.coverage }}
      JANK_ANALYZE: ${{ matrix.analyze }}
      JANK_SANITIZE: ${{ matrix.sanitize }}
      ASAN_OPTIONS: detect_leaks=0
      TERM: xterm
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install coz
        run: |
          sudo apt-get update
          sudo apt-get install -y libdwarf-dev
          sudo apt-get install -y nodejs npm
          sudo apt-get install -y build-essential cmake docutils-common git python3 pkg-config
          git clone https://github.com/plasma-umass/libelfin && cd libelfin && make && sudo make install && cd ..
          git clone https://github.com/plasma-umass/coz && cd coz && cmake . && make && sudo make install && cd ..
          sudo ldconfig
          sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
      - name: Build and test
        run: |
          curl -sL -o install-bb https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install-bb
          sudo ./install-bb
          ./bin/jank/check_everything.clj
